from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.orm import Session

from backend.api.deps import get_db, require_roles
from backend.models.enums import UserRole
from backend.models.user import User
from backend.schemas.report import (
    ExecutiveSummaryResponse, IncidentTrendReport,
    SLAComplianceReport, TeamPerformanceReport
)
from backend.services.report_service import ReportService

router = APIRouter(prefix="/reports", tags=["Operational Insights & Reports"])

MANAGEMENT_ROLES = [UserRole.MANAGER, UserRole.ADMINISTRATOR]


@router.get(
    "/summary",
    response_model=ExecutiveSummaryResponse,
    status_code=status.HTTP_200_OK,
    summary="Executive Summary KPI metrics & AI Briefing Narrative (SRS v3.3 §4.6, §7.1)"
)
def get_executive_summary(
    start_date: Optional[datetime] = Query(None, description="Filter cases created on/after this timestamp"),
    end_date: Optional[datetime] = Query(None, description="Filter cases created on/before this timestamp"),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(*MANAGEMENT_ROLES))
):
    """
    Returns high-level KPI indicators (volume, SLA compliance, MTTR)
    along with an automated plain-language executive summary generated by Gemini.
    """
    return ReportService.get_executive_summary(db=db, start_date=start_date, end_date=end_date)


@router.get(
    "/sla-compliance",
    response_model=SLAComplianceReport,
    status_code=status.HTTP_200_OK,
    summary="Granular SLA compliance breakdown by priority tier (SRS v3.3 §4.6)"
)
def get_sla_compliance(
    start_date: Optional[datetime] = Query(None),
    end_date: Optional[datetime] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(*MANAGEMENT_ROLES))
):
    """
    Returns priority-by-priority SLA response and resolution compliance rates.
    """
    return ReportService.get_sla_compliance(db=db, start_date=start_date, end_date=end_date)


@router.get(
    "/team-performance",
    response_model=TeamPerformanceReport,
    status_code=status.HTTP_200_OK,
    summary="Workload distribution and resolution metrics across teams and operators"
)
def get_team_performance(
    start_date: Optional[datetime] = Query(None),
    end_date: Optional[datetime] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(*MANAGEMENT_ROLES))
):
    """
    Returns case handling volume, breach counts, and average resolution times for each team and operator.
    """
    return ReportService.get_team_performance(db=db, start_date=start_date, end_date=end_date)


@router.get(
    "/trends",
    response_model=IncidentTrendReport,
    status_code=status.HTTP_200_OK,
    summary="Time-series incident volume, resolution, and breach trends"
)
def get_incident_trends(
    days: int = Query(default=14, ge=1, le=90, description="Number of past days to analyze"),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(*MANAGEMENT_ROLES))
):
    """
    Returns chronological daily data points for trend charting and capacity planning.
    """
    return ReportService.get_trends(db=db, days=days)
