"""initial_schema

Revision ID: 035b0440f960
Revises: 
Create Date: 2026-09-17 12:55:59.629066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035b0440f960'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('oauth_subject_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('REQUESTER', 'OPERATOR', 'TEAM_LEAD', 'MANAGER', 'ADMINISTRATOR', name='userrole'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'AWAY', 'OFFLINE', name='availabilitystatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_subject_id'), 'users', ['oauth_subject_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_site'), 'users', ['site'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('INCIDENT', 'SERVICE_REQUEST', 'PROBLEM', 'CHANGE', name='casetype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEW', 'IN_ASSESSMENT', 'ASSIGNED', 'AWAITING_REQUESTER', 'AWAITING_APPROVAL', 'PENDING', 'RESOLVED', 'CLOSED', 'CANCELLED', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='casepriority'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_owner_id'), 'cases', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_reference_number'), 'cases', ['reference_number'], unique=True)
    op.create_index(op.f('ix_cases_requester_id'), 'cases', ['requester_id'], unique=False)
    op.create_index(op.f('ix_cases_service_id'), 'cases', ['service_id'], unique=False)
    op.create_index(op.f('ix_cases_site'), 'cases', ['site'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_team_id'), 'cases', ['team_id'], unique=False)
    op.create_index(op.f('ix_cases_type'), 'cases', ['type'], unique=False)
    op.create_table('ai_triage_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.Column('suggested_severity', sa.String(length=50), nullable=True),
    sa.Column('suggested_priority', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='confidencelevel'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('supporting_factors', sa.JSON(), nullable=False),
    sa.Column('missing_info', sa.JSON(), nullable=False),
    sa.Column('suggested_team', sa.String(length=100), nullable=True),
    sa.Column('recommended_next_action', sa.String(length=255), nullable=True),
    sa.Column('related_case_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvaldecision'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_case_id'), 'attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by'), 'attachments', ['uploaded_by'], unique=False)
    op.create_table('case_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('related_case_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('RELATED_TO', 'DUPLICATE_OF', 'PART_OF_MAJOR_INCIDENT', name='caserelationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_relationships_case_id'), 'case_relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_relationships_related_case_id'), 'case_relationships', ['related_case_id'], unique=False)
    op.create_table('case_risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_risk_assessments_risk_level'), 'case_risk_assessments', ['risk_level'], unique=False)
    op.create_table('case_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('last_source_message_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('escalation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('trigger_reason', sa.Enum('APPROACHING_DEADLINE', 'MISSED_DEADLINE', 'HIGH_RISK', 'REPEATED_REOPEN', 'OPERATOR_REQUESTED', name='escalationtriggerreason'), nullable=False),
    sa.Column('escalated_to', sa.String(length=100), nullable=False),
    sa.Column('escalated_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='escalationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_events_case_id'), 'escalation_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_escalation_events_status'), 'escalation_events', ['status'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='knowledgestate'), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('source_case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_state'), 'knowledge_articles', ['state'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_title'), 'knowledge_articles', ['title'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('REQUESTER_VISIBLE', 'INTERNAL_ONLY', name='messagevisibility'), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_visibility'), 'messages', ['visibility'], unique=False)
    op.create_table('slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('target_response_at', sa.DateTime(), nullable=False),
    sa.Column('target_resolve_at', sa.DateTime(), nullable=False),
    sa.Column('first_responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_breached', sa.Boolean(), nullable=False),
    sa.Column('resolve_breached', sa.Boolean(), nullable=False),
    sa.Column('paused_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_slas_resolve_breached'), 'slas', ['resolve_breached'], unique=False)
    op.create_index(op.f('ix_slas_response_breached'), 'slas', ['response_breached'], unique=False)
    op.create_index(op.f('ix_slas_target_resolve_at'), 'slas', ['target_resolve_at'], unique=False)
    op.create_index(op.f('ix_slas_target_response_at'), 'slas', ['target_response_at'], unique=False)
    op.create_table('communication_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('draft_type', sa.Enum('INFO_REQUEST', 'PROGRESS_UPDATE', 'RESOLUTION', 'ESCALATION_SUMMARY', name='drafttype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'DISCARDED', name='draftstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('sent_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_drafts_case_id'), 'communication_drafts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_drafts_case_id'), table_name='communication_drafts')
    op.drop_table('communication_drafts')
    op.drop_index(op.f('ix_slas_target_response_at'), table_name='slas')
    op.drop_index(op.f('ix_slas_target_resolve_at'), table_name='slas')
    op.drop_index(op.f('ix_slas_response_breached'), table_name='slas')
    op.drop_index(op.f('ix_slas_resolve_breached'), table_name='slas')
    op.drop_table('slas')
    op.drop_index(op.f('ix_messages_visibility'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_articles_title'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_state'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_escalation_events_status'), table_name='escalation_events')
    op.drop_index(op.f('ix_escalation_events_case_id'), table_name='escalation_events')
    op.drop_table('escalation_events')
    op.drop_table('case_summaries')
    op.drop_index(op.f('ix_case_risk_assessments_risk_level'), table_name='case_risk_assessments')
    op.drop_table('case_risk_assessments')
    op.drop_index(op.f('ix_case_relationships_related_case_id'), table_name='case_relationships')
    op.drop_index(op.f('ix_case_relationships_case_id'), table_name='case_relationships')
    op.drop_table('case_relationships')
    op.drop_index(op.f('ix_attachments_uploaded_by'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_case_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('ai_triage_results')
    op.drop_index(op.f('ix_cases_type'), table_name='cases')
    op.drop_index(op.f('ix_cases_team_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_site'), table_name='cases')
    op.drop_index(op.f('ix_cases_service_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_requester_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_owner_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_site'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_subject_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
